import org.apache.tools.ant.filters.ReplaceTokens

version=new File("${projectDir}/../../VERSION").text.trim()
def hunspellDir="${projectDir}/../hunspell/build/hunspell"

println "Version: $version"

def subname = ""

if( project.hasProperty("type") ) {
    if( project.getProperty("type") == "nolat" ) subname = "nolat"

    logger.lifecycle("Building type: ${subname}")
}

task prepareFiles {

  doLast() {

    copy {
        from("$hunspellDir/$subname/uk_UA.aff") {
            rename "uk_UA", "uk-UA"
        }
        from("$hunspellDir/$subname/uk_UA.dic") {
            rename "uk_UA", "uk-UA"
        }
        from "meta-xpi/README_uk_UA.txt"
        into "build/xpi/dictionaries"
    }

    copy {
        from("meta-xpi/manifest.json") {
            filter(ReplaceTokens, tokens: [VERSION: project.version])
        }
        from("meta-xpi/") {
            include "*.png"
        }
        into "build/xpi"
    }
  }
}

task xpi (type: Zip, dependsOn: prepareFiles) {
    def infix = subname ? "_${subname}" : ""
    from 'build/xpi'
    archiveBaseName = "ukrainian_dictionary-$project.version-mozilla$infix"
    archiveExtension = "xpi"
    destinationDirectory = file("build")

    outputs.files "$archiveBaseName.$archiveExtension"
}
